### ISSUE TITLE
fix duplicate `destinations` field in traffic shifting rule

### ISSUE THREAD

**Issue by ilackarms** [solo-io/supergloo#452]
currently traffic shifting rule looks like this:

```
  spec:
    trafficShifting:
      destinations:
        destinations:
        - destination:
            upstream:
              name: svc-v2
              namespace: namespace1
```

we should remove the duplicated `destinations` field here
