### ISSUE TITLE
set mesh stats does not resync after config map is reset

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/supergloo#455]
steps:
- call `supergloo set mesh stats ...`
  - supergloo applies prom stats to target config map as expected
- reset the config map
  - supergloo **does not** restore the mesh stats [1]
- call above set mesh stats command again
  - supergloo **still** does not restore the mesh stats [2]

issue:
- I think [1] is ok
- I think [2] is a bug

identified while testing glooshot with this (mesh crd snippet):
```
    monitoringConfig:
      prometheusConfigmaps:
      - name: glooshot-prometheus-server
        namespace: glooshot
```
